# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noosphere-scheduler
services:
  noosphere-scheduler:
    image: ghcr.io/hpp-io/noosphere-scheduler:test
    container_name: noosphere-scheduler
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mysql://noosphere-mysql:3306/scheduler?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://noosphere-mysql:3306/scheduler?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    volumes:
      - /data/noosphere/config/hpp-keystore.p12:/app/hpp-keystore.p12
      - /data/noosphere/logs/scheduler-logs:/app/logs
    ports:
      - 8185:8185
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
